var CP = {
  codigopenal: [
    {
      id: 1,
      artigo: "12",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Arma Classe 1",
      descricao: "Porte ou posse ilegal de armamento de baixo calibre.",
      multa: 3000,
      tempoPrisao: 25,
    },
    {
      id: 2,
      artigo: "13",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Arma Classe 2",
      descricao: "Porte ou posse ilegal de armamento de médio calibre.",
      multa: 5000,
      tempoPrisao: 29,
    },
    {
      id: 3,
      artigo: "14",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Arma Classe 3",
      descricao: "Porte ou posse ilegal de armamento de alto calibre.",
      multa: 9000,
      tempoPrisao: 31,
    },
    {
      id: 4,
      artigo: "16",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Munição",
      descricao: "Portar munições de qualquer calibre até 30 unidades.",
      multa: 6000,
      tempoPrisao: 20,
    },
    {
      id: 5,
      artigo: "17",
      categoria: "pena",
      nome: "Tráfico de Munições",
      descricao: "Portar munições, dolo presumido. A partir de 31 unidades.",
      multa: 8800,
      tempoPrisao: 25,
    },
    {
      id: 6,
      artigo: "18",
      categoria: "pena",
      nome: "Tráfico de Armamento",
      descricao: "Portar dois ou mais armamentos, independente do calibre.",
      multa: 15000,
      tempoPrisao: 30,
    },
    {
      id: 7,
      artigo: "19",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Dispositivo Explosivo.",
      descricao: "Portar qualquer dispositivo explosivo.",
      multa: 35000,
      tempoPrisao: 45,
    },
    {
      id: 8,
      artigo: "20",
      categoria: "pena",
      nome: "Tráfico de Dispositivo Explosivo.",
      descricao:
        "Portar dispositivo explosivo, dolo presumido. (Se for de substâncias explosivas ou acessórios que, isoladamente ou em conjunto, permitam sua fabricação, montagem ou uso.)",
      multa: 60500,
      tempoPrisao: 60,
    },
    {
      id: 9,
      artigo: "32",
      categoria: "pena",
      nome: "Porte ou Posse de Drogas",
      descricao: " Portar drogas. Até 10 unidades",
      multa: 1000,
      tempoPrisao: 10,
    },
    {
      id: 9,
      artigo: "33",
      categoria: "pena",
      nome: "Tráfico de Drogas",
      descricao:
        "Posse ou porte de entorpecentes, dolo presumido. A partir de 10 unidades.",
      multa: 2500,
      tempoPrisao: 15,
    },
    {
      id: 10,
      artigo: "121",
      categoria: "pena",
      nome: "Homicídio",
      descricao: "Matar alguém.",
      multa: 30000,
      tempoPrisao: 80,
    },
    {
      id: 11,
      artigo: "121-A",
      categoria: "pena",
      nome: "Homicídio Qualificado",
      descricao:
        " Matar alguém com as seguintes qualificadoras: mediante paga ou promessa de recompensa, ou por outro motivo torpe; por motivo fútil; com fogo, explosivo, tortura ou outro meio insidioso ou cruel, ou de que possa resultar perigo comum; à traição, de emboscada, ou mediante dissimulação ou outro recurso que dificulte ou torne impossível a defesa do ofendido;",
      multa: 50000,
      tempoPrisao: 160,
    },
    {
      id: 12,
      artigo: "121-B",
      categoria: "pena",
      nome: "Homicídio Culposo",
      descricao: "Matar alguém por imprudência, negligência ou imperícia.",
      multa: 25000,
      tempoPrisao: 45,
    },
    {
      id: 13,
      artigo: "121-C",
      categoria: "pena",
      nome: "Homicídio Tentado",
      descricao:
        "Tentativa de homicídio não consumado por circunstâncias alheias à vontade.",
      multa: 19500,
      tempoPrisao: 30,
    },
    {
      id: 14,
      artigo: "121-D",
      categoria: "pena",
      nome: "Feminicídio",
      descricao: "Matar mulher por razões de condição de sexo feminino.",
      multa: 45500,
      tempoPrisao: 100,
    },
    {
      id: 15,
      artigo: "121-E",
      categoria: "pena",
      nome: "Homicídio de Agente Público",
      descricao:
        "Matar agente ou funcionário público, no exercício da função ou em razão dela.",
      multa: 75000,
      tempoPrisao: 175,
    },
    {
      id: 16,
      artigo: "129",
      categoria: "pena",
      nome: "Lesão Corporal",
      descricao: "Ofender a integridade física ou saúde de outrem.",
      multa: 9500,
      tempoPrisao: 17,
    },
    {
      id: 17,
      artigo: "135",
      categoria: "pena",
      nome: "Omissão de Socorro",
      descricao:
        "Causador do dano ou lesão abandona o local sem prestar socorro.",
      multa: 10000,
      tempoPrisao: 25,
    },
    {
      id: 18,
      artigo: "135-A",
      categoria: "pena",
      nome: "Omissão de Socorro de Agente Responsável",
      descricao: "Agente público que, podendo agir, não socorre vítima.",
      multa: 16000,
      tempoPrisao: 28,
    },
    {
      id: 19,
      artigo: "147",
      categoria: "pena",
      nome: "Ameaça",
      descricao: "Ameaçar alguém de causar mal injusto e grave.",
      multa: 5500,
      tempoPrisao: 15,
    },
    {
      id: 20,
      artigo: "148",
      categoria: "pena",
      nome: "Sequestro e Cárcere Privado",
      descricao: "Privar alguém de sua liberdade.",
      multa: 27000,
      tempoPrisao: 45,
    },
    {
      id: 21,
      artigo: "150",
      categoria: "pena",
      nome: "Roubo",
      descricao: "Subtrair coisa móvel alheia, para si ou para outrem, mediante violência ou grave ameaça.",
      multa: 15000,
      tempoPrisao: 25,
    },
    {
      id: 22,
      artigo: "155",
      categoria: "pena",
      nome: "Furto",
      descricao: "Subtrair, para si ou para outrem, coisa alheia móvel.",
      multa: 8000,
      tempoPrisao: 15,
    },
    {
      id: 23,
      artigo: "157",
      categoria: "pena",
      nome: "Latrocínio",
      descricao: "Subtrair coisa móvel alheia, mediante violência ou grave ameaça, com o fim de assenhorear-se definitivamente do objeto.",
      multa: 35000,
      tempoPrisao: 60,
    },
    {
      id: 24,
      artigo: "163",
      categoria: "pena",
      nome: "Extorsão",
      descricao: "Constranger alguém, mediante violência ou grave ameaça, e com intuito de obter para si ou para outrem indevida vantagem econômica, a fazer, tolerar que se faça ou deixar de fazer alguma coisa.",
      multa: 20000,
      tempoPrisao: 35,
    },
    {
      id: 25,
      artigo: "171",
      categoria: "pena",
      nome: "Estelionato",
      descricao: "Obter, para si ou para outrem, vantagem ilícita, em prejuízo alheio, induzindo ou mantendo alguém em erro, mediante artifício, ardil, ou qualquer outro meio fraudulento.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 26,
      artigo: "180",
      categoria: "pena",
      nome: "Receptação",
      descricao: "Adquirir, receber, transportar, conduzir ou ocultar, em proveito próprio ou alheio, coisa que sabe ser produto de crime, ou influir para que terceiro, de boa-fé, a adquira, receba ou oculte.",
      multa: 10000,
      tempoPrisao: 18,
    },
    {
      id: 27,
      artigo: "213",
      categoria: "pena",
      nome: "Estupro",
      descricao: "Constranger alguém, mediante violência ou grave ameaça, a ter conjunção carnal ou a praticar ou permitir que com ele se pratique outro ato libidinoso.",
      multa: 40000,
      tempoPrisao: 90,
    },
    {
      id: 28,
      artigo: "217-A",
      categoria: "pena",
      nome: "Estupro de Vulnerável",
      descricao: "Ter conjunção carnal ou praticar outro ato libidinoso com menor de 14 anos.",
      multa: 50000,
      tempoPrisao: 120,
    },
    {
      id: 29,
      artigo: "235",
      categoria: "pena",
      nome: "Falsidade Ideológica",
      descricao: "Omitir, em documento público ou particular, declaração que dele devia constar, ou nele inserir ou fazer inserir declaração falsa ou diversa da que devia ser escrita, com o fim de prejudicar direito, criar obrigação ou alterar a verdade sobre fato juridicamente relevante.",
      multa: 15000,
      tempoPrisao: 25,
    },
    {
      id: 30,
      artigo: "297",
      categoria: "pena",
      nome: "Falsificação de Documento Público",
      descricao: "Falsificar, no todo ou em parte, documento público, ou alterar documento público verdadeiro.",
      multa: 18000,
      tempoPrisao: 30,
    },
    {
      id: 31,
      artigo: "312",
      categoria: "pena",
      nome: "Peculato",
      descricao: "Apropriar-se o funcionário público de dinheiro, valor ou qualquer outro bem móvel, público ou particular, de que tem a posse em razão do cargo, ou desviá-lo, em proveito próprio ou alheio.",
      multa: 25000,
      tempoPrisao: 40,
    },
    {
      id: 32,
      artigo: "319",
      categoria: "pena",
      nome: "Prevaricação",
      descricao: "Retardar ou deixar de praticar, indevidamente, ato de ofício, ou praticá-lo contra disposição expressa de lei, para satisfazer interesse ou sentimento pessoal.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 33,
      artigo: "330",
      categoria: "pena",
      nome: "Desacato",
      descricao: "Desacatar funcionário público no exercício da função ou em razão dela.",
      multa: 8000,
      tempoPrisao: 15,
    },
    {
      id: 34,
      artigo: "331",
      categoria: "pena",
      nome: "Desobediência",
      descricao: "Desobedecer a ordem legal de funcionário público.",
      multa: 6000,
      tempoPrisao: 12,
    },
    {
      id: 35,
      artigo: "332",
      categoria: "pena",
      nome: "Resistência",
      descricao: "Opor-se à execução de ato legal, mediante violência ou ameaça a funcionário competente para executá-lo ou a quem esteja prestando auxílio.",
      multa: 10000,
      tempoPrisao: 18,
    },
    {
      id: 36,
      artigo: "333",
      categoria: "pena",
      nome: "Desacato a Tribunal",
      descricao: "Desacatar, em juízo ou fora dele, juiz, membro do Ministério Público, jurado, escrivão, oficial de justiça, perito, tradutor, intérprete ou testemunha.",
      multa: 15000,
      tempoPrisao: 25,
    },
    {
      id: 37,
      artigo: "334",
      categoria: "pena",
      nome: "Desobediência a Decisão Judicial",
      descricao: "Desobedecer a decisão judicial sobre perda ou suspensão de direito, interdição, busca e apreensão, remoção de pessoas e coisas, ou desocupação de imóvel.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 38,
      artigo: "335",
      categoria: "pena",
      nome: "Supressão ou Alteração de Marca em Animais",
      descricao: "Suprimir ou alterar marca em animais de outrem.",
      multa: 5000,
      tempoPrisao: 10,
    },
    {
      id: 39,
      artigo: "336",
      categoria: "pena",
      nome: "Usurpação de Propriedade",
      descricao: "Usurpar o uso de nome alheio ou apropriar-se de ou atribuir a outrem falsa identidade para obter vantagem, em proveito próprio ou alheio, ou para causar dano.",
      multa: 8000,
      tempoPrisao: 15,
    },
    {
      id: 40,
      artigo: "337",
      categoria: "pena",
      nome: "Falsidade de Atestado Médico",
      descricao: "Falsificar atestado ou declaração de doença ou incapacidade para o trabalho, ou fazer declaração falsa sobre estas circunstâncias.",
      multa: 10000,
      tempoPrisao: 18,
    },
    {
      id: 41,
      artigo: "338",
      categoria: "pena",
      nome: "Falsidade de Atestado de Óbito",
      descricao: "Falsificar atestado de óbito ou declaração de morte.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 42,
      artigo: "339",
      categoria: "pena",
      nome: "Falsidade de Atestado de Nascimento",
      descricao: "Falsificar atestado ou declaração de nascimento.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 43,
      artigo: "340",
      categoria: "pena",
      nome: "Falsidade de Atestado de Casamento",
      descricao: "Falsificar atestado ou declaração de casamento.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 44,
      artigo: "341",
      categoria: "pena",
      nome: "Falsidade de Atestado de Divórcio",
      descricao: "Falsificar atestado ou declaração de divórcio.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 45,
      artigo: "342",
      categoria: "pena",
      nome: "Falsidade de Atestado de Separação",
      descricao: "Falsificar atestado ou declaração de separação.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 46,
      artigo: "343",
      categoria: "pena",
      nome: "Falsidade de Atestado de Adoção",
      descricao: "Falsificar atestado ou declaração de adoção.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 47,
      artigo: "344",
      categoria: "pena",
      nome: "Falsidade de Atestado de Naturalização",
      descricao: "Falsificar atestado ou declaração de naturalização.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 48,
      artigo: "345",
      categoria: "pena",
      nome: "Falsidade de Atestado de Cidadania",
      descricao: "Falsificar atestado ou declaração de cidadania.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 49,
      artigo: "346",
      categoria: "pena",
      nome: "Falsidade de Atestado de Residência",
      descricao: "Falsificar atestado ou declaração de residência.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 50,
      artigo: "347",
      categoria: "pena",
      nome: "Falsidade de Atestado de Trabalho",
      descricao: "Falsificar atestado ou declaração de trabalho.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 51,
      artigo: "348",
      categoria: "pena",
      nome: "Falsidade de Atestado de Estudo",
      descricao: "Falsificar atestado ou declaração de estudo.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 52,
      artigo: "349",
      categoria: "pena",
      nome: "Falsidade de Atestado de Capacidade",
      descricao: "Falsificar atestado ou declaração de capacidade.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 53,
      artigo: "350",
      categoria: "pena",
      nome: "Falsidade de Atestado de Sanidade",
      descricao: "Falsificar atestado ou declaração de sanidade.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 54,
      artigo: "351",
      categoria: "pena",
      nome: "Falsidade de Atestado de Invalidez",
      descricao: "Falsificar atestado ou declaração de invalidez.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 55,
      artigo: "352",
      categoria: "pena",
      nome: "Falsidade de Atestado de Morte",
      descricao: "Falsificar atestado ou declaração de morte.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 56,
      artigo: "353",
      categoria: "pena",
      nome: "Falsidade de Atestado de Nascimento",
      descricao: "Falsificar atestado ou declaração de nascimento.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 57,
      artigo: "354",
      categoria: "pena",
      nome: "Falsidade de Atestado de Casamento",
      descricao: "Falsificar atestado ou declaração de casamento.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 58,
      artigo: "355",
      categoria: "pena",
      nome: "Falsidade de Atestado de Divórcio",
      descricao: "Falsificar atestado ou declaração de divórcio.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 59,
      artigo: "356",
      categoria: "pena",
      nome: "Falsidade de Atestado de Separação",
      descricao: "Falsificar atestado ou declaração de separação.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 60,
      artigo: "357",
      categoria: "pena",
      nome: "Falsidade de Atestado de Adoção",
      descricao: "Falsificar atestado ou declaração de adoção.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 61,
      artigo: "358",
      categoria: "pena",
      nome: "Falsidade de Atestado de Naturalização",
      descricao: "Falsificar atestado ou declaração de naturalização.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 62,
      artigo: "359",
      categoria: "pena",
      nome: "Falsidade de Atestado de Cidadania",
      descricao: "Falsificar atestado ou declaração de cidadania.",
      multa: 12000,
      tempoPrisao: 20,
    },
    {
      id: 63,
      artigo: "113",
      categoria: "multa",
      nome: "Condições Mínimas de Circulação",
      descricao: "Conduzir veículo com ausência de componentes mínimos para locomoção segura, como rodas, volante, bancos ou sistema de direção funcional.",
      multa: 12200,
      tempoPrisao: 0,
    },
    {
      id: 64,
      artigo: "114",
      categoria: "multa",
      nome: "Excesso de Fumaça, Ruído ou Poluição",
      descricao: "Conduzir veículo que emita, de forma excessiva, fumaça, barulho ou outros elementos poluentes.",
      multa: 1800,
      tempoPrisao: 0,
    },
    {
      id: 65,
      artigo: "115",
      categoria: "multa",
      nome: "Uso de Som Excessivo em Veículos",
      descricao: "Emitir som ou música em volume excessivo, perturbando o sossego público ou o funcionamento de órgãos públicos.",
      multa: 2000,
      tempoPrisao: 0,
    },
    {
      id: 66,
      artigo: "116",
      categoria: "multa",
      nome: "Modificações Visuais ou Estruturais Irregulares",
      descricao: "Circular com veículo que possua modificações não autorizadas, que comprometam a identificação ou segurança.",
      multa: 3000,
      tempoPrisao: 0,
    },
    {
      id: 67,
      artigo: "117",
      categoria: "multa",
      nome: "Buzina ou Sirene em Local Inadequado",
      descricao: "Uso de buzina, alarme ou sirene fora de situação de risco ou emergência.",
      multa: 5000,
      tempoPrisao: 0,
    },
    {
      id: 68,
      artigo: "118",
      categoria: "multa",
      nome: "Falta de Equipamentos Obrigatórios",
      descricao: "Circular sem um ou mais dos equipamentos obrigatórios em bom estado: faróis, espelhos, freios, setas, buzina, limpadores ou cinto.",
      multa: 7500,
      tempoPrisao: 0,
    },
    {
      id: 69,
      artigo: "119",
      categoria: "multa",
      nome: "Veículo com Peças Faltantes",
      descricao: "Conduzir veículo automotor com ausência de peças essenciais à sua integridade estrutural ou à segurança da condução, tais como: portas, capô, para-brisa, para-lamas, retrovisores ou bancos.",
      multa: 6000,
      tempoPrisao: 0,
    },
    {
      id: 70,
      artigo: "120",
      categoria: "multa",
      nome: "Pneus em Estado Crítico",
      descricao: "Conduzir veículo com pneus severamente desgastados, com sulcos irregulares, lisos (carecas), ou com estrutura metálica exposta.",
      multa: 6500,
      tempoPrisao: 0,
    },
    {
      id: 71,
      artigo: "121",
      categoria: "multa",
      nome: "Ausência de Equipamentos de Segurança Obrigatórios",
      descricao: "Conduzir veículo com um ou mais dos seguintes itens ausentes ou inoperantes: freios, faróis, lanternas, espelhos retrovisores, setas, buzina, limpador de para-brisa, cinto de segurança ou sistema de direção.",
      multa: 9800,
      tempoPrisao: 0,
    },
    {
      id: 72,
      artigo: "122",
      categoria: "multa",
      nome: "Modificações Mecânicas Perigosas",
      descricao: "Modificar partes mecânicas do veículo de forma a comprometer sua estabilidade ou segurança, tais como: rebaixamento extremo da suspensão; retirada ou modificação de escapamento com corte direto; uso de rodas fora do padrão estrutural original; modificação do sistema de direção ou de frenagem.",
      multa: 9800,
      tempoPrisao: 0,
    },
    {
      id: 73,
      artigo: "123",
      categoria: "multa",
      nome: "Estrutura Comprometida por Colisão",
      descricao: "Conduzir veículo com a estrutura comprometida por acidente anterior, com indícios visíveis de desalinhamento, empenamento, risco de ruptura ou soldagem irregular.",
      multa: 19200,
      tempoPrisao: 0,
    },
  ],
}; 